// -----------------------------------------------------------------------------
// Configuration: defaults, normalization and validation.
//
// The user fills the form generated by Gladys from the manifest
// `config_schema`; the SDK hands us the raw values (strings, numbers,
// booleans, or nothing at all for a field never saved). Everything the rest
// of the code reads goes through `normalizeConfig()`, so the defaults live in
// one place and stay aligned with the manifest (see test/manifest.test.js).
// -----------------------------------------------------------------------------

export const DEFAULT_CONFIG = {
  frigate_url: '',
  username: '',
  password: '',
  allow_self_signed: false,
  snapshot_height: 480,
  snapshot_interval: 60,
};

// Gladys accepts at most 12 camera images per minute and per device.
export const MIN_SNAPSHOT_INTERVAL = 5;
export const MAX_SNAPSHOT_INTERVAL = 3600;
export const MIN_SNAPSHOT_HEIGHT = 120;
export const MAX_SNAPSHOT_HEIGHT = 1080;

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function toNumber(value, fallback) {
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

/**
 * Merge the raw user configuration with the defaults.
 * @param {Record<string, unknown>} [raw] configuration returned by the SDK
 */
export function normalizeConfig(raw = {}) {
  const interval = Math.round(toNumber(raw.snapshot_interval, DEFAULT_CONFIG.snapshot_interval));
  return {
    frigate_url: String(raw.frigate_url ?? '')
      .trim()
      .replace(/\/+$/, ''),
    username: String(raw.username ?? '').trim(),
    password: String(raw.password ?? ''),
    allow_self_signed: raw.allow_self_signed === true,
    snapshot_height: clamp(
      Math.round(toNumber(raw.snapshot_height, DEFAULT_CONFIG.snapshot_height)),
      MIN_SNAPSHOT_HEIGHT,
      MAX_SNAPSHOT_HEIGHT,
    ),
    // 0 disables the periodic snapshots (images are then only fetched on demand).
    snapshot_interval:
      interval <= 0 ? 0 : clamp(interval, MIN_SNAPSHOT_INTERVAL, MAX_SNAPSHOT_INTERVAL),
  };
}

/**
 * Check that the configuration is usable.
 * @param {ReturnType<typeof normalizeConfig>} config
 * @returns {{ en: string, fr: string } | null} a user-facing error, or null
 */
export function validateConfig(config) {
  if (!config.frigate_url) {
    return {
      en: 'Enter the URL of your Frigate server in the configuration.',
      fr: "Renseignez l'URL de votre serveur Frigate dans la configuration.",
    };
  }
  let url;
  try {
    url = new URL(config.frigate_url);
  } catch {
    url = null;
  }
  if (!url || !['http:', 'https:'].includes(url.protocol) || !url.hostname) {
    return {
      en: 'The Frigate URL must look like http://192.168.1.10:5000 or https://192.168.1.10:8971.',
      fr: "L'URL de Frigate doit ressembler à http://192.168.1.10:5000 ou https://192.168.1.10:8971.",
    };
  }
  if (url.username || url.password) {
    return {
      en: 'Do not put credentials in the Frigate URL: use the username and password fields.',
      fr: "Ne mettez pas d'identifiants dans l'URL de Frigate : utilisez les champs utilisateur et mot de passe.",
    };
  }
  if (Boolean(config.username) !== Boolean(config.password)) {
    return {
      en: 'Fill in both the Frigate username and password, or leave both empty.',
      fr: "Renseignez à la fois l'utilisateur et le mot de passe Frigate, ou laissez les deux vides.",
    };
  }
  return null;
}
